# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.1.0

jobs:
  test:
    docker:
      - image: 'cimg/node:22.5.1-browsers'
    steps:
      - browser-tools/install-chrome
      - checkout
      - node/install-packages
      - run: ./node_modules/.bin/ember test --silent --r xunit > ./tests/results.xml
      - store_test_results:
          path: ./tests/results.xml

  build-deploy:
    docker:
      - image: 'cimg/node:22.5.1-browsers'
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - store_artifacts:
          path: ./dist/
      - run:
          name: Deploy on Firebase
          command: |
            echo $SA_KEY > credentials.json
            GOOGLE_APPLICATION_CREDENTIALS=credentials.json firebase deploy
    
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-test-deploy: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - test
      - build-deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
